version: 2
updates:
    - package-ecosystem: npm
      directory: /eslint-plugin
      schedule:
          interval: daily
      ignore:
          - dependency-name: "prettier*"

    - package-ecosystem: npm
      directory: /prettier-config
      schedule:
          interval: daily
