version: 2
updates:
    - package-ecosystem: npm
      directory: /eslint-plugin
      schedule:
          interval: daily

    - package-ecosystem: npm
      directory: /prettier-config
      schedule:
          interval: daily
